# node-graphql-lesson-04/docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: factory_game_db_${ENV}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data_${ENV}:/var/lib/postgresql/data

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: factory_frontend
    ports:
      - 4173:4173

  server:
    platform: linux/x86_64
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: factory_server
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    # restart: always

volumes:
  frontend:
  server:
  postgres_data_test:
  postgres_data_prod:
